### PR TITLE
Video performance over time report

### PR DESCRIPTION
**Pull request by diamond-darrell**

### CODE REVIEW

**Comment by amirch1** [comment]
@diamond-darrell  - looks great! for some reason, when in compare mode, the 2 lines are in the same color where the legend shows the correct 2 different colors. Happens in all 4 tabs

**Comment by amirch1** [comment]
@diamond-darrell - when deep linking to compare view (simple refresh the page when in compare view) - the tabs disappear. When exiting compare view - they reappear...

**Comment by diamond-darrell** [comment]
> @diamond-darrell - when deep linking to compare view (simply refresh the page when in compare view) - the tabs disappear. When exiting compare view - they reappear...

fixed

**Comment by diamond-darrell** [comment]
> @diamond-darrell - looks great! for some reason, when in compare mode, the 2 lines are in the same color where the legend shows the correct 2 different colors. Happens in all 4 tabs

it is strange, I don't experience this issue...
image

**Pull request merged**
